#!/bin/sh
set -e

if command -v typst 2>&1 >/dev/null; then
  for f in examples/*.typ; do
    typst compile -f png --root . "$f"
  done
else
  for f in examples/*.typ; do
    if ! git diff --quiet HEAD "$f"; then
      echo >&2 'aborting commit because '"$f"' requires recompilation, but `typst` is not installed'
      exit 1
    fi
  done
fi
